name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@d4873ceeec10de6275fecd1f94b6985369d40231
        with:
          deno-version: v1.32.5

      - name: Run build
        run: deno task build

      - name: Run static type check
        run: deno task check

      - name: Run tests
        run: deno task test
